data:
    data_path: "D:/ProjectImages/SyntheticContrast"
    target: ["AC", "VC"]
    source: ["HQ"]
    segs: ["AC"]
    times: "times_ordinal.json"
    down_sample: 1
    patch_size: [64, 64, 64]
    norm_param_1: -500
    norm_param_2: 2500
    num_examples: 4
    cv_folds: 3
    fold: 2
hyperparameters:
    img_dims: [64, 64, 64]
augmentation:
    use: true
    depth: 64
    flip_prob: 0.5
    rotation: 45.0
    scale: [0.8, 1.6]
    shear: 15.0
    translate: [0.25, 0.25]