name: contrast
channels:
  - defaults
  - conda-forge
  - simpleitk
dependencies:
  - pip=22.2.2
  - python=3.10
  - cudatoolkit=11.2
  - cudnn=8.1.0
  - matplotlib>=3.4
  - pandas>=1.3
  - pytest>=7.1.2
  - pyyaml=6.0
  - scikit-image>=0.18
  - simpleitk>=2.1
  - statsmodels=0.13
  - pip:
    - tensorflow==2.9.1
    - pytest-subtests==0.9.0